In [34]:
import numpy as np

class LinearRegressionGD:
    def __init__(self,learning_rate=0.01,epochs=100):
        self.lr=learning_rate
        self.epochs=epochs
        self.w=0
        self.b=0
        self.loss_history=[]

    def predict(self,x):
        X = np.asarray(X)
        return X @ self.weights + self.bias

    def compute_loss(self,x,y):
        y_pred=self.predict(x)
        return np.mean((y_pred-y)**2)

    def fit(self,x,y):
        n=len(x)
        for i in range(self.epochs):
            y_pred=self.predict(x)
            error=y_pred-y
            dw=(2/n)*np.sum(x*error)
            db=(2/n)*np.sum(error)

            self.w=self.w-self.lr*dw
            self.b=self.b-self.lr*db

            loss=self.compute_loss(x,y)
            self.loss_history.append(loss)

        return self

In [16]:
# Training data: hours studied
x = np.array([1, 2, 3, 4, 5], dtype=float)

# Target: exam marks
y = np.array([15, 25, 35, 45, 55], dtype=float)

model = LinearRegressionGD(
    learning_rate=0.01,
    epochs=2000
)

model.fit(x, y)

print("Weight:", model.w)
print("Bias:", model.b)
print("Final MSE:", model.loss_history[-1])

print("Prediction for 6 hours:",
      model.predict(np.array([6.0])))

Weight: 10.000656214653619
Bias: 4.997630856884656
Final MSE: 1.0216349159921403e-06
Prediction for 6 hours: [65.00156814]

In [ ]:
import kagglehub
data_dir = "./data"
path = kagglehub.dataset_download("lainguyn123/student-performance-factors",output_dir=data_dir)

print("Path to dataset files:", path)

In [18]:
import pandas as pd

df=pd.read_csv('./data/StudentPerformanceFactors.csv')
df.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [19]:
print(df.isnull().sum())

Hours_Studied                  0
Attendance                     0
Parental_Involvement           0
Access_to_Resources            0
Extracurricular_Activities     0
Sleep_Hours                    0
Previous_Scores                0
Motivation_Level               0
Internet_Access                0
Tutoring_Sessions              0
Family_Income                  0
Teacher_Quality               78
School_Type                    0
Peer_Influence                 0
Physical_Activity              0
Learning_Disabilities          0
Parental_Education_Level      90
Distance_from_Home            67
Gender                         0
Exam_Score                     0
dtype: int64

In [20]:
df1=df.dropna()

In [21]:
df1.head()

,Hours_Studied,Attendance,Parental_Involvement,Access_to_Resources,Extracurricular_Activities,Sleep_Hours,Previous_Scores,Motivation_Level,Internet_Access,Tutoring_Sessions,Family_Income,Teacher_Quality,School_Type,Peer_Influence,Physical_Activity,Learning_Disabilities,Parental_Education_Level,Distance_from_Home,Gender,Exam_Score
0,23,84,Low,High,No,7,73,Low,Yes,0,Low,Medium,Public,Positive,3,No,High School,Near,Male,67
1,19,64,Low,Medium,No,8,59,Low,Yes,2,Medium,Medium,Public,Negative,4,No,College,Moderate,Female,61
2,24,98,Medium,Medium,Yes,7,91,Medium,Yes,2,Medium,Medium,Public,Neutral,4,No,Postgraduate,Near,Male,74
3,29,89,Low,Medium,Yes,8,98,Medium,Yes,1,Medium,Medium,Public,Negative,4,No,High School,Moderate,Male,71
4,19,92,Medium,Medium,Yes,6,65,Medium,Yes,3,Medium,High,Public,Neutral,4,No,College,Near,Female,70

In [22]:
df1.isnull().sum()

Hours_Studied                 0
Attendance                    0
Parental_Involvement          0
Access_to_Resources           0
Extracurricular_Activities    0
Sleep_Hours                   0
Previous_Scores               0
Motivation_Level              0
Internet_Access               0
Tutoring_Sessions             0
Family_Income                 0
Teacher_Quality               0
School_Type                   0
Peer_Influence                0
Physical_Activity             0
Learning_Disabilities         0
Parental_Education_Level      0
Distance_from_Home            0
Gender                        0
Exam_Score                    0
dtype: int64

In [24]:
X = df.select_dtypes(include='number').drop(columns=['Exam_Score'])
y=df['Exam_Score']

from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

x_train,x_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=2)

In [25]:
model1=LinearRegression()
model1.fit(x_train,y_train)
y_pred=model1.predict(x_test)

from sklearn.metrics import r2_score,mean_squared_error

print(r2_score(y_test,y_pred))
print(mean_squared_error(y_test,y_pred))

0.5495484838715989
7.749323663678251

In [ ]:
model2=LinearRegressionGD(learning_rate=0.01,epochs=5)
model2.fit(x_train,y_train)
X_new = np.array([[23, 84, 7, 73, 0, 3]])
print(model2.predict(X_new))

In [38]:
print("X shape:", x_train.shape)
print("y shape:", y_train.shape)
print("Weights shape:", model.w.shape)
print("New input shape:", X_new.shape)

X shape: (5285, 6)
y shape: (5285,)
Weights shape: ()
New input shape: (1, 6)

In [31]:
x_train.shape

(5285, 6)